services:
  db:
    container_name: ${DB_HOST}
    image: ${DB_IMAGE}:${DB_TAG}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-trn-net

  web:
    container_name: ${WEB_HOST}
    image: ${WEB_IMAGE_NAME}:${WEB_IMAGE_TAG}
    build: ./
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:8069"
      - "${WEB_GEVENT_PORT}:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
#    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"
    networks:
      - odoo-trn-net

  pgbouncer:
    container_name: ${PGB_HOST}
    image: edoburu/pgbouncer:latest
    depends_on:
      - db
    ports:
      - "${PGB_PORT}:5432"
    volumes:
      - ./pgbouncer:/etc/pgbouncer
#    environment:
#      - "DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}"
#      - DB_HOST=db
#      - DB_USER=odoo
#      - DB_PASSWORD=odoo
#      - POOL_MODE=transaction
#      - MAX_CLIENT_CONN=500
    networks:
      - odoo-trn-net

volumes:
  odoo-db-data:
  odoo-web-data:

networks:
  odoo-trn-net: