# -*- coding: utf-8 -*-
import io
import logging
import tempfile

from odoo import models, fields, api
import csv
import os, errno
from datetime import date, datetime, timedelta
import base64
import xlwt
from jinja2 import Environment
import pdfkit
from decimal import Decimal, ROUND_HALF_UP

_logger = logging.getLogger(__name__)

try:
    import openpyxl
except ImportError:
    _logger.debug("Can not import openpyxl")


class ReportDefinition(models.Model):
    _name = "report.definition"
    _description = "Report Definitions"
    _active_name = "active"
    _order = "id desc"

    def name_get(self):
        data = []
        for record in self:
            display_value = "({}) - {}".format(record.export_as, record.name)
            data.append((record.id, display_value))
        return data

    name = fields.Char(string="Report Name")
    query = fields.Text(string="Report Query")
    export_fields = fields.Text(string="Export Fields")
    export_as = fields.Selection(
        [
            ("xls", "XLS File"),
            ("xlsx", "XLSX File"),
            ("csv", "CSV File"),
            ("pdf", "PDF File"),
            ("txt", "TEXT File"),
        ]
    )
    template_id = fields.Many2one("report.template")
    test_html = fields.Text(string="Test HTML")
    report_paperformat_id = fields.Many2one("report.paperformat", string="Paper Format")
    state = fields.Selection(
        [("draft", "Draft"), ("posted", "Posted")], default="draft", string="Status"
    )
    noupdate = fields.Boolean(default=False)
    active = fields.Boolean(default=True)
    rename_fields = fields.Boolean(default=False)
    new_name_fields = fields.Text(string="Name Fields")

    def test_generate_report(self):
        format_date = "%Y-%m-%d"
        start_date = datetime.strptime(str(date.today()), format_date) - timedelta(
            days=30
        )
        # branch = self.env['company.branches'].search([])
        filter_data = {"start_date": str(start_date), "end_date": str(date.today())}

        if "%(company_id)s" in self.query:
            filter_data["company_id"] = self.env.company.id
        query = str(self.query) % filter_data
        self.env.cr.execute(query)
        results = self.env.cr.dictfetchall()
        export_fields = eval(self.export_fields)
        script_path = os.path.dirname(os.path.abspath(__file__))
        #         default header
        header = """
            <div class="px-4 py-4">
            <h2>Test %s</h2>
            </div>
        """ % (
            self.name
        )

        #         default body
        body = """
        <table class="table table-striped">
          <tbody>
            {% for result in results %}
            <tr>
                {% for rest in result %}
                  <td>{{rest}}</td>
                {% endfor %}
            </tr>
            {% endfor %}
          </tbody>
        </table>

"""

        template = {"title": "", "body": body, "header": header, "footer": ""}

        #         check if it has own template and report pdf
        if self.template_id and self.export_as == "pdf":
            template["header"] = self.template_id.header
            template["body"] = self.template_id.body
            template["footer"] = self.template_id.footer

        else:
            data = []
            data.append(export_fields)
            for result in results:
                data_result = []
                for field in export_fields:
                    if field in result:
                        data_result.append(result[field])
                data.append(data_result)

            results = data

        #         parameter that will be generated by jinja2

        # < link
        # rel = "stylesheet"
        # href = "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        # integrity = "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
        # crossorigin = "anonymous" >
        csstemplates = [
            {"url": "/byc_report_creator/static/src/css/bootstrap.min.css"},
            {"url": "/web/static/src/css/reset.min.css"},
            {"url": "/byc_report_creator/static/src/css/paper_style.css"},
        ]
        render_vars = {
            "results": results,
            "title": self.name,
            "css_templates": csstemplates,
            "c_page_size": "A4",
        }
        HTML = f"""
                <!DOCTYPE html>
                <html lang="es_BO">
                <html>

                    <head>
                        <meta charset="UTF-8">
                        <meta http-equiv="X-UA-Compatible" content="IE=edge">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        <title>{{{{ title }}}}</title>
                            {{% for enlace in css_templates -%}}
                                <link rel="stylesheet" href="{{{{ enlace['url'] }}}}" />
                            {{% endfor -%}}
                        <style>
                            @page {{
                              size: {{{{ c_page_size }}}};
                            }}
                        </style>
                    </head>
                    <body class="{{{{ c_page_size }}}}">
                        <div class="sheet px-5 py-5">
                            {template['header']}
                            {template['body']}
                            {template['footer']}
                        </body>
                    </div>
                </html>
                """

        #         get the result of html in string
        result_html = Environment().from_string(HTML).render(render_vars)

        #         store the string html tag to the test_html field
        self.test_html = result_html

        #         return url so it will redirect to this url
        return {
            "type": "ir.actions.act_url",
            "name": "report",
            "url": "/web/test?model=report.definition&id=%s" % (self.id),
        }

    def write(self, vals):
        # for val in vals:
        #     if 'noupdate' in val and val.get('noupdate', False):
        return super(ReportDefinition, self).write(vals)


class ReportTemplate(models.Model):
    _name = "report.template"
    _description = "Report Templates"
    _order = "name asc, id desc"
    _active_name = "active"

    name = fields.Char(string="Name")
    header = fields.Text(string="Header")
    body = fields.Text(string="Body")
    footer = fields.Text(string="Footer")
    active = fields.Boolean(default=True)


class ReportResult(models.Model):
    _name = "report.result"
    _description = "Report Results"
    _order = "date_generated desc"
    _active_name = "active"

    name = fields.Many2one("report.definition", string="Report Name")
    attachment_file = fields.Binary("File", compute="_get_file_report")
    file_report_name = fields.Char(string="File Report Name")
    path_file = fields.Char(string="Path File")
    date_generated = fields.Date(string="Date Generated")
    active = fields.Boolean(default=True)

    #     get the data from the server, not save it in database but in file system

    def _get_file_report(self):
        try:
            file = open(str(self.path_file), "rb")
            if file:
                self.attachment_file = base64.b64encode(file.read())
        except:
            self.attachment_file = False

    # main function to call first
    def generate_report(self, data):
        report_def_obj = data["report_def_obj"]
        filter_data = {
            "start_date": data["start_date"],
            "end_date": data["end_date"],
            "company_id": data["company_id"],
        }
        query = str(report_def_obj.query) % filter_data
        print_header = data["print_header"]
        separator = data["separator"]
        paired_columns = data["paired_columns"]
        self.env.cr.execute(
            query,
        )
        results = self.env.cr.dictfetchall()
        export_fields = eval(report_def_obj.export_fields)
        # config = self.env["res.config.settings"].sudo().get_path()
        # file_store = str(config["file_store"])
        file_store = self.env.company.file_store or "/tmp/"
        file_store = os.path.join(file_store, str(date.today()))
        paper_format = report_def_obj.report_paperformat_id

        result_data = self.create(
            {"name": int(report_def_obj.id), "date_generated": str(date.today())}
        )

        #         define data for generate
        data_rpt = {
            "file_store": file_store,
            "export_fields": export_fields,
            "result_id": result_data.id,
            "results": results,
            "report_def_obj": report_def_obj,
        }

        #         create directory to store file report
        self.create_directory(data_rpt)

        #         check the condition report
        if report_def_obj.export_as == "xls":
            path_file, report_name = self.generate_xls(data_rpt)
        elif report_def_obj.export_as == "xlsx":
            path_file, report_name = self.generate_xlsx(data_rpt)
        elif report_def_obj.export_as == "csv":
            path_file, report_name = self.generate_csv(data_rpt)

        elif report_def_obj.export_as == "pdf":
            path_file, report_name = self.generate_pdf(data_rpt, paper_format)

        elif report_def_obj.export_as == "txt":
            path_file, report_name = self.GenerateTxt(data_rpt, print_header, separator)

        result_data.path_file = str(path_file)
        result_data.file_report_name = str(report_name)
        result_data.name = int(report_def_obj.id)

    def generate_report_v2(self, data):
        report_def_obj = data["report_def_obj"]
        company_id = data["partner_id"]
        filter_data = self._get_filters(data, company_id)
        query = str(report_def_obj.query) % filter_data
        # -print('query---->>>***', query)
        print_header = data["print_header"]
        separator = data["separator"]
        paired_columns = data["paired_columns"]
        self.env.cr.execute(
            query,
        )
        results = self.env.cr.dictfetchall()
        export_fields = eval(report_def_obj.export_fields)
        # file_store = self.env.company.file_store or '/tmp/'

        file_store = "/tmp/"  # os.path.join(file_store, str(date.today()))
        paper_format = report_def_obj.report_paperformat_id

        result_data = self.create(
            {"name": int(report_def_obj.id), "date_generated": str(date.today())}
        )

        #         define data for generate
        data_rpt = {
            "file_store": file_store,
            "export_fields": export_fields,
            "result_id": result_data.id,
            "results": results,
            "report_def_obj": report_def_obj,
        }

        #         create directory to store file report
        # self.create_directory(data_rpt)
        file_data = report_name = None
        #         check the condition report
        if report_def_obj.export_as == "xls":
            file_data, report_name = self.generate_xlsx(data_rpt)
        elif report_def_obj.export_as == "xlsx":
            file_data, report_name = self.generate_xlsx(data_rpt)
        elif report_def_obj.export_as == "csv":
            path_file, report_name = self.generate_csv(data_rpt)

        elif report_def_obj.export_as == "pdf":
            file_data, report_name = self.generate_pdf(data_rpt, paper_format)

        elif report_def_obj.export_as == "txt":
            file_data, report_name = self.generate_txt_raw(
                data_rpt, print_header, separator
            )

        return file_data, report_name, report_def_obj.export_as

    #     function create directory
    def create_directory(self, data_rpt):
        # script_path = str(os.path.dirname(__file__)).replace("/models", "")
        # full_path = os.path.join(script_path, str(data_rpt['file_store']))
        full_path = str(data_rpt["file_store"])
        if not os.path.exists(full_path):
            os.makedirs(full_path)
        else:
            print(str(os.path.exists(full_path)) + " directory already exists")

    #     function for generate csv file
    def generate_csv(self, data_rpt):
        #         store the all data in data list
        data = []
        data.append(data_rpt["export_fields"])
        for result in data_rpt["results"]:
            data_result = []
            for field in data_rpt["export_fields"]:
                if field in result:
                    data_result.append(result[field])
            data.append(data_result)

        #         define the name of the report and path to store it
        report_name = (
            data_rpt["report_def_obj"].name
            + "-"
            + str(date.today())
            + "-"
            + str(data_rpt["result_id"])
            + ".csv"
        )
        path_file = os.path.join(data_rpt["file_store"], report_name)

        #         create csv file and store it in file system
        with open(path_file, "w") as csvFile:
            writer = csv.writer(csvFile)
            writer.writerows(data)
        csvFile.close()

        return path_file, report_name

    #     function for generate pdf file
    def generate_pdf(self, data_rpt, paper_format=False):
        script_path = str(os.path.dirname(__file__)).replace("/models", "")
        bootstrap_css = os.path.join(
            script_path, "models/html/bootstrap/bootstrap.min.css"
        )
        resetmin_css = os.path.join(script_path, "models/html/bootstrap/reset.min.css")
        paper_css = os.path.join(script_path, "models/html/bootstrap/paper_style.css")
        file_store = os.path.join(script_path, data_rpt["file_store"])
        template = {
            "header": data_rpt["report_def_obj"].template_id.header
            if data_rpt["report_def_obj"].template_id.header
            else "",
            "body": data_rpt["report_def_obj"].template_id.body,
            "footer": data_rpt["report_def_obj"].template_id.footer
            if data_rpt["report_def_obj"].template_id.footer
            else "",
        }
        format_tmpl = ""
        if paper_format:
            format_tmpl = (
                """<meta name="pdfkit-page-size" content="{p1}"/>""".format(
                    p1=paper_format.format
                )
                + "\n"
            )
            format_tmpl += (
                """<meta name="pdfkit-orientation" content="{p1}"/>""".format(
                    p1=paper_format.orientation
                )
                + "\n"
            )
            format_tmpl += (
                """<meta name="pdfkit-margin-top" content="{p1}mm"/>""".format(
                    p1=paper_format.margin_top
                )
                + "\n"
            )
            format_tmpl += (
                """<meta name="pdfkit-margin-right" content="{p1}mm"/>""".format(
                    p1=paper_format.margin_right
                )
                + "\n"
            )
            format_tmpl += (
                """<meta name="pdfkit-margin-bottom" content="{p1}mm"/>""".format(
                    p1=paper_format.margin_bottom
                )
                + "\n"
            )
            format_tmpl += (
                """<meta name="pdfkit-margin-left" content="{p1}mm"/>""".format(
                    p1=paper_format.margin_left
                )
                + "\n"
            )
            format_tmpl += (
                """<meta name="pdfkit-dpi" content="{p1}"/>""".format(
                    p1=paper_format.dpi
                )
                + "\n"
            )
        #         main html structure

        css_templates = [
            {"url": script_path + "/static/src/css/bootstrap.min.css"},
            {"url": script_path + "/static/src/css/reset.min.css"},
            {"url": script_path + "/static/src/css/paper_style.css"},
        ]
        # render_vars = {
        #     "results": data_rpt['results'],
        #     "css_templates": css_templates,
        #     "title": data_rpt['report_def_obj'].name + '_' + str(date.today()),
        #     "formato_papel": format_tmpl,
        # }
        # HTML = f'''
        #         <!DOCTYPE html>
        #         <html>
        #             <head>
        #                 <meta charset="UTF-8">
        #                 {{{{formato_papel}}}}
        #                 <title>{{{{title}}}}</title>
        #                     {{% for enlace in css_templates -%}}
        #                         <link rel="stylesheet" href="{{{{ enlace['url'] }}}}" />
        #                     {{% endfor -%}}

        #             </head>
        #             <body class="container">
        #                <div class="box">
        #                     <div class="header row">
        #                          {template['header']}
        #                     </div>
        #                     <div class="article row">
        #                         {template['body']}
        #                     </div>
        #                     <div class="footer row">
        #                            {template['footer']}
        #                     </div>
        #                </div>
        #             </body>
        #         </html>

        #         '''

        HTML = f"""<!DOCTYPE html>
<html lang="es_BO">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {{{{formato_papel}}}}
        <title>{{{{ title }}}}</title>
        <link rel="stylesheet" type="text/css" href="{{{{bootstrap_css}}}}">
        <link rel="stylesheet" type="text/css" href="{{{{resetmin_css}}}}">
        <link rel="stylesheet" type="text/css" href="{{{{paper_css}}}}">

    </head>
    <body class="container">
        <div class="box">
            <div class="row header">
                {template['header']}
            </div>
            <div class="row article">
                {template['body']}
            </div>
            <div class="row footer">
                {template['footer']}
            </div>
        </div>
    </body>
</html>"""

        render_vars = {
            "results": data_rpt["results"],
            "title": data_rpt["report_def_obj"].name + "_" + str(date.today()),
            "bootstrap_css": bootstrap_css,
            "resetmin_css": resetmin_css,
            "paper_css": paper_css,
            "formato_papel": format_tmpl,
        }
        # render_vars = {
        #     "results": data_rpt['results'],
        #     "css_templates": css_templates,
        #     "title": data_rpt['report_def_obj'].name + '_' + str(date.today()),
        #     "formato_papel": format_tmpl,
        # }
        result_html = Environment().from_string(HTML).render(render_vars)

        #         define the name of the report and path to store it
        report_name = (
            data_rpt["report_def_obj"].name
            + "_"
            + str(date.today())
            + "_"
            + str(data_rpt["result_id"])
            + ".pdf"
        )

        # formato de papel para la generación del pdf

        #         create pdf file and store it in file system
        # -print("--->> Html Pdf", template["body"])
        css = [bootstrap_css, resetmin_css, paper_css]

        # configure PDF pages
        options = None
        if paper_format:
            pf = paper_format
            # options = {
            #     'dpi': pf.dpi,
            #     'page-size': pf.format,
            #     'encoding': "UTF-8",
            #     'margin-top': pf.margin_top,
            #     'margin-right': pf.margin_right,
            #     'margin-bottom': pf.margin_bottom,
            #     'margin-left': pf.margin_left,
            #     'enable-internal-links': '',
            # 'footer-center': '[page] of [topage]',
            # 'header-html': _path + '/web/templates/web/pdf/header.html',
            # 'footer-html': _path + '/web/templates/web/pdf/footer.html',
            # 'page-offset': '-1',
            # 'dump-outline': _path + '/web/templates/web/pdf/outline.xslt'
            # 'header-spacing': '4',
            # 'footer-spacing': '2'
            # }
        file_data = pdfkit.from_string(result_html, False, options=options)
        # pdfkit.from_string(result_html, file_store, options=options, css=css)
        with open(file_store + "/index.html", "w") as filetmp:
            filetmp.write(result_html)
        filetmp.close()
        return file_data, report_name

    #     function for generate xls file
    def generate_xls(self, data_rpt):
        wb = xlwt.Workbook()
        ws = wb.add_sheet(data_rpt["report_def_obj"].name)

        #         store the all data in data list
        data = []
        data.append(data_rpt["export_fields"])
        for result in data_rpt["results"]:
            data_result = []
            for field in data_rpt["export_fields"]:
                if field in result:
                    data_result.append(result[field])
            data.append(data_result)

        #         write data in sheet xls
        row = 0
        for data_row in data:
            col = 0
            for data_col in data_row:
                ws.write(row, col, data_col)
                col += 1
            row += 1

        #         define the name of the report and path to store it
        report_name = (
            data_rpt["report_def_obj"].name
            + "_"
            + str(date.today())
            + "_"
            + str(data_rpt["result_id"])
            + ".xls"
        )
        path_file = os.path.join(data_rpt["file_store"], report_name)

        #         save xls file
        wb.save(path_file)
        return path_file, report_name

    def generate_xlsx(self, data_rpt):
        data = [data_rpt["export_fields"]]
        for result in data_rpt["results"]:
            data_result = []
            for field in data_rpt["export_fields"]:
                if field in result:
                    data_result.append(result[field])
            data.append(data_result)
        report_name = (
            data_rpt["report_def_obj"].name
            + "_"
            + str(date.today())
            + "_"
            + str(data_rpt["result_id"])
            + ".xlsx"
        )
        wb = openpyxl.Workbook()
        ws = wb.active
        row_position = 1
        col_position = 1
        for index, row in enumerate(data, row_position):
            for col, val in enumerate(row, col_position):
                ws.cell(row=index, column=col).value = val
        output = io.BytesIO()
        wb.save(output)
        output.getvalue()
        # file_data = base64.b64encode(output.getvalue())
        file_data = output.getvalue()
        output.close()
        return file_data, report_name

    #     function for generate csv file
    def GenerateTxt(self, data_rpt, print_h=False, separator=",", paired_columns=True):
        #         store the all data in data list
        data = []
        sheader = ""
        if print_h:
            for header in data_rpt["export_fields"]:
                sheader += str(header + separator)
            if len(sheader) > 1:
                sheader = sheader[0 : len(sheader) - 1]
            data.append(sheader + "\n")

        p_col = paired_columns

        for result in data_rpt["results"]:
            for field in data_rpt["export_fields"]:
                if field in result:
                    if isinstance(result[field], int):
                        result[field] = str(result[field])
                    elif isinstance(result[field], float):
                        monto_f = Decimal(result[field])
                        monto_f = round(
                            Decimal(
                                monto_f.quantize(
                                    Decimal("0.01"), rounding=ROUND_HALF_UP
                                )
                            ),
                            2,
                        )
                        result[field] = str(monto_f)
                    elif isinstance(result[field], datetime):
                        result[field] = datetime.strftime(result[field], "%d/%m/%Y")
                    elif isinstance(result[field], date):
                        result[field] = datetime.strftime(result[field], "%d/%m/%Y")

        vector = []
        if p_col:
            for result in data_rpt["results"]:
                pos = 0
                for field in data_rpt["export_fields"]:
                    vector.append(0)
                    if field in result:
                        size = len(str(result[field]))
                        if size > vector[pos]:
                            vector[pos] = size
                    pos += 1

        for result in data_rpt["results"]:
            row = ""
            pos = 0
            for field in data_rpt["export_fields"]:
                if field in result:
                    if p_col:
                        row += (
                            self._calculate_size_field(str(result[field]), vector[pos])
                            + separator
                        )
                    else:
                        row += str(result[field]) + separator
                pos += 1

            if len(row) > 1:
                row = row[0 : len(row) - 1]
            data.append(row + "\n")

        # define the name of the report and path to store it
        report_name = (
            data_rpt["report_def_obj"].name
            + "-"
            + str(date.today())
            + "-"
            + str(data_rpt["result_id"])
            + ".txt"
        )
        path_file = os.path.join(data_rpt["file_store"], report_name)

        #         create csv file and store it in file system
        with open(path_file, "w") as txtFile:
            txtFile.writelines(data)
        txtFile.close()

        return path_file, report_name

    def generate_txt_raw(
        self, data_rpt, print_h=False, separator=",", paired_columns=True
    ):
        #         store the all data in data list
        data = []
        sheader = ""
        separator = "\t" if separator == "TAB" else separator
        if print_h:
            for header in data_rpt["export_fields"]:
                sheader += str(header + separator)
            if len(sheader) > 1:
                sheader = sheader[0 : len(sheader) - 1]
            data.append(sheader + "\n")

        p_col = paired_columns

        for result in data_rpt["results"]:
            for field in data_rpt["export_fields"]:
                if field in result:
                    if isinstance(result[field], int):
                        result[field] = str(result[field])
                    elif isinstance(result[field], float):
                        monto_f = Decimal(result[field])
                        monto_f = round(
                            Decimal(
                                monto_f.quantize(
                                    Decimal("0.01"), rounding=ROUND_HALF_UP
                                )
                            ),
                            2,
                        )
                        result[field] = str(monto_f)
                    elif isinstance(result[field], datetime):
                        result[field] = datetime.strftime(result[field], "%d/%m/%Y")
                    elif isinstance(result[field], date):
                        result[field] = datetime.strftime(result[field], "%d/%m/%Y")

        vector = []
        if p_col:
            for result in data_rpt["results"]:
                pos = 0
                for field in data_rpt["export_fields"]:
                    vector.append(0)
                    if field in result:
                        size = len(str(result[field]))
                        if size > vector[pos]:
                            vector[pos] = size
                    pos += 1

        for result in data_rpt["results"]:
            row = ""
            pos = 0
            for field in data_rpt["export_fields"]:
                if field in result:
                    if p_col:
                        row += (
                            self._calculate_size_field(str(result[field]), vector[pos])
                            + separator
                        )
                    else:
                        row += str(result[field]) + separator
                pos += 1

            if len(row) > 1:
                row = row[0 : len(row) - 1]
            data.append(row + "\n")

        # define the name of the report and path to store it
        report_name = (
            data_rpt["report_def_obj"].name
            + "-"
            + str(date.today())
            + "-"
            + str(data_rpt["result_id"])
            + ".txt"
        )
        path_file = os.path.join(data_rpt["file_store"], report_name)

        with io.StringIO() as file_tmp:
            file_tmp.writelines(data)
            file_tmp.seek(0)
            file_data = str.encode(file_tmp.getvalue(), "utf-8")
        file_tmp.close()

        return file_data, report_name

        #         create csv file and store it in file system
        # with tempfile.TemporaryFile(mode='w+',encoding='utf-8') as fp:
        #     fp.writelines(data)
        #     fp.seek(0)
        #     file_data = str.encode(fp.read(),'utf-8')
        # fp.close()
        # return file_data, report_name

    #     function for button download
    def download_report(self):
        return {
            "type": "ir.actions.act_url",
            "name": "report",
            "url": "/web/content/report.result/%s/attachment_file/%s?download=true"
            % (self.id, self.file_report_name),
        }

    def _calculate_size_field(self, cadena, cant):
        while len(cadena) < cant:
            cadena += " "
        return cadena

    def _get_filters(self, data, company_id):
        filter_data = {
            "start_date": data["start_date"],
            "end_date": data["end_date"],
            "company_id": company_id,
        }
        return filter_data
